

install:
	mkdir -p /usr/share/jolla-settings/pages/text_input
	cp textinput_inky.qml /usr/share/jolla-settings/pages/text_input/
	mkdir -p /usr/share/qt5/keymaps
	cp inky.qmap /usr/share/qt5/keymaps/

all: install
